//! Integration tests that wire `pc-typescript-gen` to the real `pc-openapi`
//! DTO registry (35 schemas registered by `register_core_dtos`).

use pc_openapi::{register_core_dtos, OpenApiRegistry, CORE_DTO_NAMES};
use pc_typescript_gen::{generate_typescript_types, schema_to_typescript, schema_to_type_expr};
use serde_json::json;

fn build_real_spec() -> pc_openapi::OpenApiSpec {
    let mut reg = OpenApiRegistry::builder();
    register_core_dtos(&mut reg);
    reg.build()
}

#[test]
fn real_spec_generates_for_all_35_dtos() {
    let spec = build_real_spec();
    let ts = generate_typescript_types(&spec);
    for name in CORE_DTO_NAMES {
        let pascal = to_pascal(name);
        assert!(
            ts.contains(&format!("export interface {pascal}"))
                || ts.contains(&format!("export type {pascal}")),
            "missing DTO {name} (PascalCase {pascal}) in generated output"
        );
    }
}

#[test]
fn real_spec_output_is_byte_stable() {
    let spec = build_real_spec();
    let ts1 = generate_typescript_types(&spec);
    let ts2 = generate_typescript_types(&spec);
    assert_eq!(ts1, ts2, "generator output is not deterministic");
}

#[test]
fn real_spec_header_present() {
    let spec = build_real_spec();
    let ts = generate_typescript_types(&spec);
    assert!(ts.starts_with("// Generated by pc-typescript-gen (R518)"));
}

#[test]
fn real_spec_no_empty_interface_bodies() {
    // Schemas without named properties should fall back to `type X = ...`,
    // never `interface X { }`. We assert that any `interface X {` line is
    // followed by an indented property (not immediately by `}`).
    let spec = build_real_spec();
    let ts = generate_typescript_types(&spec);
    let mut in_interface = false;
    let mut saw_property = false;
    for line in ts.lines() {
        if line.starts_with("export interface ") {
            in_interface = true;
            saw_property = false;
            continue;
        }
        if in_interface {
            if line.starts_with("  ") && line.ends_with(";") {
                saw_property = true;
            } else if line == "}" {
                assert!(
                    saw_property,
                    "interface with empty body found:\n{ts}"
                );
                in_interface = false;
            }
        }
    }
    // Verify we also emitted type aliases for non-object DTOs.
    assert!(ts.contains("export type "), "no type aliases emitted");
}

#[test]
fn real_spec_contains_at_least_33_exports() {
    let spec = build_real_spec();
    let ts = generate_typescript_types(&spec);
    let export_count = ts.matches("export ").count();
    assert!(
        export_count >= CORE_DTO_NAMES.len(),
        "expected at least {} exports, got {}",
        CORE_DTO_NAMES.len(),
        export_count
    );
}

#[test]
fn decision_schema_includes_status_enum_as_union() {
    let spec = build_real_spec();
    let ts = generate_typescript_types(&spec);
    assert!(ts.contains("Decision"), "Decision interface missing");
    assert!(ts.contains("|"), "no union types in generated output");
}

#[test]
fn schema_to_type_expr_handles_top_level_array() {
    let out = schema_to_type_expr(&json!({"type": "array", "items": {"type": "string"}}), &[]);
    assert_eq!(out, "string[]");
}

#[test]
fn schema_to_typescript_for_single_inline_object() {
    let schema = json!({
        "type": "object",
        "required": ["id"],
        "properties": {
            "id": {"type": "string"},
            "count": {"type": "integer"}
        }
    });
    let out = schema_to_typescript("Ping", &schema);
    assert!(out.contains("export interface Ping"));
    assert!(out.contains("id: string;"));
    assert!(out.contains("count?: number;"));
}

// Mirror to_pascal_case locally so we can assert without exposing the helper.
fn to_pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut at_start = true;
    for c in s.chars() {
        if c.is_alphanumeric() {
            if at_start {
                out.extend(c.to_uppercase());
                at_start = false;
            } else {
                out.push(c);
            }
        } else {
            at_start = true;
        }
    }
    out
}

#[test]
fn generated_types_pass_tsc_strict_check() {
    // Write the generated output to a temp file and parse it with the
    // local TypeScript compiler. This catches wire-format drift between
    // the Rust emitter and the actual TS syntax that downstream tools
    // (UI client, IDE type-checking, CI) will see.
    use std::io::Write;
    use std::process::{Command, Stdio};

    let spec = build_real_spec();
    let ts = generate_typescript_types(&spec);

    let mut tmp = tempfile();
    tmp.write_all(ts.as_bytes()).unwrap();

    // Locate tsc. Prefer the system PATH; fall back to npx tsc.
    let candidates: [(&str, Vec<&str>); 2] = [
        ("tsc", vec!["--noEmit", "--strict", "--target", "es2020", "--ignoreConfig", "--module", "esnext", "--moduleResolution", "bundler"]),
        ("npx", vec!["--yes", "typescript@5", "--", "tsc", "--noEmit", "--strict", "--target", "es2020", "--ignoreConfig", "--module", "esnext", "--moduleResolution", "bundler"]),
    ];

    let mut last_err = String::new();
    for (cmd, args) in &candidates {
        let output = Command::new(cmd)
            .args(args)
            .arg(tmp.path())
            .stdin(Stdio::null())
            .output();
        match output {
            Ok(o) if o.status.success() => return, // tsc OK
            Ok(o) => {
                last_err = format!(
                    "{cmd} failed: stdout={}, stderr={}",
                    String::from_utf8_lossy(&o.stdout),
                    String::from_utf8_lossy(&o.stderr)
                );
            }
            Err(e) => last_err = format!("{cmd} not available: {e}"),
        }
    }
    panic!("tsc verification failed: {last_err}");
}

fn tempfile() -> tempfile_proxy::NamedTempFile {
    tempfile_proxy::NamedTempFile::new().unwrap()
}

mod tempfile_proxy {
    use std::fs::File;
    use std::io::{Read, Seek, SeekFrom, Write};
    use std::path::{Path, PathBuf};

    pub struct NamedTempFile {
        path: PathBuf,
    }

    impl NamedTempFile {
        pub fn new() -> std::io::Result<Self> {
            use std::time::{SystemTime, UNIX_EPOCH};
            let nanos = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();
            let pid = std::process::id();
            let path = std::env::temp_dir().join(format!("pc-typescript-gen-{pid}-{nanos}.ts"));
            Ok(Self { path })
        }

        pub fn path(&self) -> &Path { &self.path }

        pub fn write_all(&mut self, buf: &[u8]) -> std::io::Result<()> {
            let mut f = File::create(&self.path)?;
            f.write_all(buf)
        }
    }

    impl Drop for NamedTempFile {
        fn drop(&mut self) {
            let _ = std::fs::remove_file(&self.path);
        }
    }

    // Suppress unused warnings from Seek/Read trait imports.
    #[allow(dead_code)]
    fn _u(_f: &mut File, _: u64) -> std::io::Result<u64> {
        _f.seek(SeekFrom::Start(0)).map(|_| 0)
    }
    #[allow(dead_code)]
    fn _r(_f: &mut File) -> std::io::Result<()> {
        let mut s = String::new();
        _f.read_to_string(&mut s).map(|_| ())
    }
}
