//! Summary slots 路由契约测试。

use std::sync::Arc;

use axum::{body::Body, http::Request};
use pc_adapter_api::AdapterRegistry;
use pc_core::ActorRegistry;
use pc_heartbeat::spawn_heartbeat_supervisor;
use pc_http::{
    routes,
    state::{ConfigSnapshot, RuntimeHandles},
    AppState,
};
use pc_realtime::{RealtimeHandle, WsState};
use pc_repos::Db;
use serde_json::{json, Value};
use tokio::sync::Mutex as AsyncMutex;
use tower::ServiceExt;
use uuid::Uuid;

static TEST_LOCK: AsyncMutex<()> = AsyncMutex::const_new(());

const TEST_DATABASE_URL: &str = "postgres://paperclip:paperclip@127.0.0.1:5432/paperclip_repos";

fn test_state(db: Db) -> AppState {
    let actors = ActorRegistry::new();
    let realtime = RealtimeHandle::start(64);
    AppState::new(
        db.clone(),
        RuntimeHandles {
            heartbeat: spawn_heartbeat_supervisor(4, actors.clone()),
            agents: pc_agent::spawn_agent_supervisor(db),
            adapters: AdapterRegistry::new(),
            actors,
        },
        ConfigSnapshot {
            host: "127.0.0.1".into(),
            port: 3100,
            session_cookie: "paperclip_session".into(),
            api_key_header: "x-paperclip-agent-key".into(),
            csrf_header: "x-paperclip-csrf".into(),
        },
        pc_telemetry::TelemetryOptions::default(),
        Arc::new(WsState::new(realtime.clone(), "test".to_string())),
        realtime,
    )
}

async fn insert_company(db: &Db) -> Uuid {
    let id = Uuid::new_v4();
    sqlx::query(
        "INSERT INTO companies (id, name, status, issue_prefix, created_at, updated_at) \
         VALUES ($1, $2, 'active', $3, now(), now())",
    )
    .bind(id)
    .bind(format!("ss-{id}"))
    .bind(id.simple().to_string())
    .execute(db.pool())
    .await
    .expect("insert company");
    id
}

async fn call(app: &axum::Router, method: &str, path: &str, body: Option<Value>) -> (u16, Value) {
    let _guard = TEST_LOCK.lock().await;
    let payload = body
        .as_ref()
        .map(|v| serde_json::to_vec(v).expect("serialize"))
        .unwrap_or_default();
    let response = app
        .clone()
        .oneshot(
            Request::builder()
                .method(method)
                .header("content-type", "application/json")
                .uri(path)
                .body(Body::from(payload))
                .expect("request"),
        )
        .await
        .expect("response");
    let status = response.status().as_u16();
    let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .expect("read body");
    let payload = if bytes.is_empty() {
        Value::Null
    } else {
        serde_json::from_slice(&bytes).unwrap_or(Value::Null)
    };
    (status, payload)
}

#[tokio::test(flavor = "current_thread")]
async fn summary_slot_get_returns_null_when_missing() {
    let db = Db::connect(TEST_DATABASE_URL, 4, 0).await.expect("connect");
    let company_id = insert_company(&db).await;
    let app = routes::summary_slots::router().with_state(test_state(db));
    let slot_key = format!("slot-{}", Uuid::new_v4().simple());
    let (status, body) = call(
        &app,
        "GET",
        &format!("/api/companies/{company_id}/summary-slots/company/{slot_key}"),
        None,
    )
    .await;
    assert_eq!(status, 200, "get missing: {body}");
    assert!(body["slot"].is_null(), "slot should be null: {body}");
    assert!(
        body["document"].is_null(),
        "document should be null: {body}"
    );
    assert!(body["generatingIssue"].is_null());
}

#[tokio::test(flavor = "current_thread")]
async fn summary_slot_put_creates_slot_and_document_then_get_returns_it() {
    let db = Db::connect(TEST_DATABASE_URL, 4, 0).await.expect("connect");
    let company_id = insert_company(&db).await;
    let app = routes::summary_slots::router().with_state(test_state(db.clone()));
    let scope_id = Uuid::new_v4();
    let slot_key = format!("slot-{}", Uuid::new_v4().simple());

    // PUT (create slot + document)
    let (status, body) = call(
        &app,
        "PUT",
        &format!("/api/companies/{company_id}/summary-slots/company/{slot_key}?scopeId={scope_id}"),
        Some(json!({
            "markdown": "# Initial summary\n\nGenerated by Rust summary-slot API.",
            "title": "Initial",
            "changeSummary": "first generation",
            "model": "test-model"
        })),
    )
    .await;
    assert_eq!(status, 200, "put: {body}");
    let slot_id = body["slot"]["id"].as_str().expect("slot id");
    assert_eq!(body["slot"]["status"], "idle");
    assert_eq!(body["slot"]["scopeKind"], "company");
    assert_eq!(body["document"]["format"], "markdown");
    assert_eq!(body["document"]["latestRevisionNumber"], json!(1));
    let document_id = body["document"]["id"].as_str().expect("document id");

    // GET returns slot + document
    let (status, body) = call(
        &app,
        "GET",
        &format!("/api/companies/{company_id}/summary-slots/company/{slot_key}?scopeId={scope_id}"),
        None,
    )
    .await;
    assert_eq!(status, 200);
    assert_eq!(body["slot"]["id"], slot_id);
    assert_eq!(body["document"]["id"], document_id);

    // PUT again → revision 2
    let (status, body) = call(
        &app,
        "PUT",
        &format!("/api/companies/{company_id}/summary-slots/company/{slot_key}?scopeId={scope_id}"),
        Some(json!({
            "markdown": "# Updated\n\nSecond generation.",
            "title": "Updated",
            "changeSummary": "second pass"
        })),
    )
    .await;
    assert_eq!(status, 200, "update: {body}");
    assert_eq!(body["document"]["latestRevisionNumber"], json!(2));

    // List revisions
    let (status, body) = call(
        &app,
        "GET",
        &format!("/api/companies/{company_id}/summary-slots/company/{slot_key}/revisions?scopeId={scope_id}"),
        None,
    )
    .await;
    assert_eq!(status, 200, "revisions: {body}");
    let revisions = body["revisions"].as_array().expect("revisions array");
    assert_eq!(revisions.len(), 2, "two revisions: {body}");
    // Newest first
    assert_eq!(revisions[0]["revisionNumber"], 2);
    assert_eq!(revisions[1]["revisionNumber"], 1);
    assert_eq!(revisions[0]["changeSummary"], "second pass");
    assert_eq!(revisions[1]["changeSummary"], "first generation");
}

#[tokio::test(flavor = "current_thread")]
async fn summary_slot_put_rejects_empty_markdown() {
    let db = Db::connect(TEST_DATABASE_URL, 4, 0).await.expect("connect");
    let company_id = insert_company(&db).await;
    let app = routes::summary_slots::router().with_state(test_state(db));
    let slot_key = format!("slot-{}", Uuid::new_v4().simple());
    let (status, body) = call(
        &app,
        "PUT",
        &format!("/api/companies/{company_id}/summary-slots/company/{slot_key}"),
        Some(json!({ "markdown": "   " })),
    )
    .await;
    assert_eq!(status, 400, "empty markdown must be rejected: {body}");
}
