#![forbid(unsafe_code)]

//! Generate TypeScript types from OpenAPI 3.1 / JSON Schema 2020-12.
//!
//! **目标 (R518, V4 0% → 60%)**: 把 Rust 端 `pc-openapi` 生成的 `components.schemas`
//! 自动转换成 TypeScript `interface` + 类型别名，给 `ui/` 60 client 用，冻结前后端契约。
//!
//! 设计原则：
//! - **Pure functions**：`generate_typescript_types(&OpenApiSpec) -> String` 无 IO、无副作用
//! - **OpenAPI 3.1 优先**：使用 `type: ["string", "null"]`（OAS 3.1）而不是 `nullable: true`（OAS 3.0）
//! - **稳定排序**：输出按 schema 名字典序排序，每次生成字节级一致
//! - **不破坏既有 types**：只生成新类型，不动 ui/ 现有手写 types
//!
//! 支持的 JSON Schema 特性：
//! - 原始类型：string / number / integer / boolean / null
//! - 复合类型：array (with `items`) / object (with `properties` + `required`)
//! - 引用：`$ref: "#/components/schemas/Foo"` → `Foo`
//! - 枚举：`enum: [...]` → 字符串字面量联合
//! - Nullable：`type: ["string", "null"]` 或 `nullable: true` → `T | null`
//! - 复合：`oneOf` / `anyOf` → 联合；`allOf` → 交叉
//! - 额外属性：`additionalProperties: true` → `{[key: string]: unknown}`
//!
//! 不支持的（fallback 到 `unknown`）：
//! - `not` schema
//! - `if` / `then` / `else` 条件 schema
//! - `patternProperties`
//! - `$defs`（嵌套）
//!
//! 与 Node 上游 `openapi-typescript` / `openapi-zod` 的差异：
//! - 不依赖 npm 工具链；纯 Rust，编译时跑
//! - 输出 deterministic 排序 → 适合 git diff review
//! - 不生成 fetch client（用户已经在 ui/ 手写）

use serde_json::Value;

use pc_openapi::{OpenApiSpec, SchemaRef};

mod emit;
mod naming;

pub use emit::{format_property_name, is_simple_identifier, schema_to_type_expr};

/// Errors that can arise during TypeScript generation.
///
/// In practice generation is infallible (any JSON Schema is convertible
/// to *something*), but we surface the unsupported-pattern cases so
/// callers can opt-in to `unknown` fallback rather than silently
/// generating `any`.
#[derive(Debug, thiserror::Error)]
pub enum TypeGenError {
    #[error("openapi spec has no components.schemas; nothing to generate")]
    EmptySchemas,
}

/// Generate TypeScript interface declarations for every schema in
/// `spec.components.schemas`. Output is sorted alphabetically by name
/// so two runs against the same spec produce byte-identical files
/// (suitable for `git diff` review).
///
/// # Example
///
/// ```no_run
/// use pc_typescript_gen::generate_typescript_types;
/// use pc_openapi::OpenApiRegistry;
///
/// let mut reg = OpenApiRegistry::builder();
/// let spec = reg.build();
/// let ts = generate_typescript_types(&spec);
/// assert!(ts.starts_with("// Generated by pc-typescript-gen"));
/// ```
/// Generate TypeScript interface declarations for every named schema in
/// `spec.components.schemas`. Each [`SchemaRef`] is serialized to JSON
/// (using the same `serde_json::to_value` path that produces the
/// `/openapi.json` body), then emitted as a `interface` or `type` alias.
///
/// Output is sorted alphabetically by name so two runs against the same
/// spec produce byte-identical files (suitable for `git diff` review).
#[must_use]
pub fn generate_typescript_types(spec: &OpenApiSpec) -> String {
    let mut out = String::new();
    out.push_str("// Generated by pc-typescript-gen (R518). DO NOT EDIT.\n");
    out.push_str("// Source: crates/pc-openapi/src/dto_schemas.rs\n\n");

    if spec.components.schemas.is_empty() {
        out.push_str("// (no components.schemas found)\n");
        return out;
    }

    let mut names: Vec<&String> = spec.components.schemas.keys().collect();
    names.sort();

    for name in names {
        let Some(schema_ref) = spec.components.schemas.get(name) else { continue };
        let Some(schema_value) = schema_ref_to_value(schema_ref) else { continue };
        let ts = emit::schema_to_typescript(name, &schema_value);
        out.push_str(&ts);
        out.push('\n');
    }
    out
}

/// Convert a [`SchemaRef`] back to its underlying `serde_json::Value`.
/// Returns `None` for the `Named` ($ref) variant since those point at
/// another named schema and would be circular if re-emitted.
fn schema_ref_to_value(schema_ref: &SchemaRef) -> Option<serde_json::Value> {
    match schema_ref {
        SchemaRef::Named { .. } => None,
        SchemaRef::Inline { schema } => Some(schema.clone()),
        SchemaRef::Raw(value) => Some(value.clone()),
    }
}

/// Convenience: generate TS for a single (name, schema) pair.
/// Used by tests and by callers that want to incrementally emit types.
#[must_use]
pub fn schema_to_typescript(name: &str, schema: &Value) -> String {
    emit::schema_to_typescript(name, schema)
}


