[package]
name = "pc-feedback-trace"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Feedback trace business service"
[lints]
workspace = true
[dependencies]
async-trait = { workspace = true }
pc-core = { path = "../pc-core" }
pc-errors = { path = "../pc-errors" }
pc-repos = { path = "../pc-repos" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
 uuid = { workspace = true }
sqlx = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
