[package]
name = "pc-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Tool application business service"
[lints]
workspace = true
[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
pc-errors = { path = "../pc-errors" }
pc-repos = { path = "../pc-repos" }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
 uuid = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
pc-core = { path = "../pc-core" }
