#!/usr/bin/env python3
"""Build `contracts/upstream-schema.sql` from the vendored upstream migrations.

The board this answers
----------------------
The plan used to *assume* which tables upstream has, and the assumption was wrong
in both directions (`docs/plan1.md` D1 claimed `issue_label` / `issue_to_label` /
`issue_property` do not exist upstream; they do).  This script replaces the
assumption with a measurement:

    replay `migrations/upstream/*.up.sql` (pinned commit, vendored byte-for-byte)
      → scratch database
      → `pg_dump --schema-only` + `information_schema`/`pg_catalog` extraction
      → `contracts/upstream-schema.sql` (human contract) + `.json` (machine form)

Both artefacts are **checked in and read-only**: CI never regenerates them, it
only reads them (`scripts/schema_drift.py`).  Regeneration is a deliberate,
reviewed act because it moves the contract the whole repo is measured against.

Pinning
-------
`migrations/upstream/PIN` records the upstream commit the vendored bytes came
from; `migrations/upstream/MANIFEST.sha256` makes them verifiable with
`sha256sum -c` *and* is verified by this script before anything is applied, so a
snapshot can never be produced from a half-edited migration set.

Recorded skips — never silent ones
----------------------------------
Three of the upstream migrations depend on extensions this PostgreSQL does not
have (`pg_bigm`, `pg_cron`), and four more hide that dependency behind a
`DO ... EXCEPTION` guard that would swallow the failure without a trace here.
This script therefore (a) probes `pg_available_extensions`, (b) skips any
statement mentioning a marker of a missing extension **before** running it, and
(c) writes every skip, plus every guard `NOTICE` PostgreSQL emitted, into
`contracts/upstream-apply-exceptions.tsv`.  A skip nobody predicted is fatal
unless `--lenient` is passed, and `schema_drift.py` refuses to exit 0 while an
exception has no row in `contracts/schema-deviations.tsv`.

Usage
-----
    export MULTICA_TEST_DATABASE_URL=postgres://multica:multica@127.0.0.1:5432/multica_test
    python3 scripts/build_upstream_schema.py                 # build + write
    python3 scripts/build_upstream_schema.py --check         # rebuild and diff, write nothing
    python3 scripts/build_upstream_schema.py --keep-db       # keep the scratch DB
    python3 scripts/build_upstream_schema.py --json          # machine-readable summary

Exit codes
----------
    0  snapshot written (or `--check` found it byte-identical); no unexpected skip
    1  snapshot written but statements had to be skipped that were not predicted
       (only reachable with `--lenient`) — the snapshot is not trustworthy yet
    2  usage/environment error: bad URL, missing psql/pg_dump, manifest mismatch,
       a migration that failed unexpectedly

`--db-url` (or `MULTICA_TEST_DATABASE_URL`) must point at an **existing**
database on the target server; the script creates the scratch database
`schema_probe_w0b_up` next to it and drops it again unless `--keep-db` is given.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from schema_snapshot import (  # noqa: E402  (path juggling is deliberate: scripts/ is not a package)
    SNAPSHOT_FORMAT,
    ApplyReport,
    ScratchDatabase,
    SchemaToolError,
    apply_migrations,
    assert_extension_markers_cover,
    build_snapshot,
    collapse_ws,
    database_name,
    normalize_dump,
    parse_db_url,
    redact,
    required_extensions,
    sha256_of,
    skip_object_keys,
    snapshot_header,
    write_text,
)

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MIGRATIONS = "migrations/upstream"
DEFAULT_MANIFEST = "migrations/upstream/MANIFEST.sha256"
DEFAULT_PIN = "migrations/upstream/PIN"
DEFAULT_OUT_SQL = "contracts/upstream-schema.sql"
DEFAULT_OUT_JSON = "contracts/upstream-schema.json"
DEFAULT_OUT_EXCEPTIONS = "contracts/upstream-apply-exceptions.tsv"
DEFAULT_DB_NAME = "schema_probe_w0b_up"
GENERATED_BY = "scripts/build_upstream_schema.py (LUM-1386, W0-B)"

TSV_TITLE = (
    "# contracts/upstream-apply-exceptions.tsv — statements skipped while building\n"
    "# contracts/upstream-schema.sql, and the guard messages PostgreSQL emitted.\n"
    "#\n"
    "# Generated by scripts/build_upstream_schema.py — do not edit by hand.  Every\n"
    "# statement-skip row is cross-checked against contracts/schema-deviations.tsv: a skip\n"
    "# with no registered deviation there fails scripts/schema_drift.py, and so does a\n"
    "# registered `apply-exception:` row with no skip here.\n"
    "#\n"
    "# category    extension-unavailable  this server lacks an extension the statement needs\n"
    "#             unsupported-statement  PostgreSQL refused the statement for another reason\n"
    "#             guard-notice           upstream wrapped the statement in DO ... EXCEPTION\n"
    "#                                    and PostgreSQL reported the skip at runtime\n"
    "# file/line    where the statement starts in the vendored file\n"
    "# objects      the keys the skipped statement was going to create, kind:name — a\n"
    "#              statement whose DDL could not be parsed is keyed `statement:<file>:<line>`\n"
    "#              so that no skip can escape contracts/schema-deviations.tsv\n"
)
TSV_COLUMNS = "# file\tline\tcategory\treason\tobjects\tstatement\n"


def migration_number(name: str) -> str:
    """The leading `<digits>_` prefix, e.g. `032_issue_search_index.up.sql` → `032`."""
    return name.split("_", 1)[0]


def read_pin(path: Path) -> dict[str, str]:
    if not path.exists():
        raise SchemaToolError(
            f"{path} is missing — it records the upstream commit the vendored migrations "
            "came from.  See docs/25-W0-SCHEMA-DRIFT.md §2 for the regeneration recipe."
        )
    pin: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        pin[key.strip()] = value.split("#")[0].strip()
    for required in ("repo", "commit"):
        if not pin.get(required):
            raise SchemaToolError(f"{path} has no `{required}:` line")
    if not re.fullmatch(r"[0-9a-f]{40}", pin["commit"]):
        raise SchemaToolError(f"{path}: commit must be a full 40-char sha, got {pin['commit']!r}")
    return pin


def verify_manifest(manifest: Path, migrations: Path, files: list[Path]) -> int:
    """Check every vendored file against `MANIFEST.sha256` (and that it is complete)."""
    if not manifest.exists():
        raise SchemaToolError(f"{manifest} is missing (sha256 manifest of the vendored migrations)")
    expected: dict[str, str] = {}
    for line in manifest.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, _, name = line.partition("  ")
        if not digest or not name:
            raise SchemaToolError(f"{manifest}: cannot parse line {line!r} (expected `<sha>  <file>`)")
        expected[name.strip()] = digest.strip()
    actual_names = {p.name for p in files}
    missing = sorted(actual_names - set(expected))
    extra = sorted(set(expected) - actual_names)
    if missing or extra:
        raise SchemaToolError(
            f"{manifest} does not describe the vendored set: unlisted={missing} stale={extra}"
        )
    bad = [p.name for p in files if sha256_of(p) != expected[p.name]]
    if bad:
        raise SchemaToolError(
            f"{manifest}: checksum mismatch for {len(bad)} file(s): {bad[:5]}"
            " — the vendored migrations must stay byte-for-byte identical to upstream"
        )
    return len(expected)


def render_exceptions(report: ApplyReport, pin: dict[str, str]) -> str:
    rows = []
    for skip in report.skipped:
        objects = ",".join(f"{kind}:{name}" for kind, name in skip_object_keys(skip))
        rows.append(
            (
                skip.file,
                str(skip.line),
                skip.category,
                collapse_ws(skip.reason),
                objects,
                collapse_ws(skip.statement)[:400],
            )
        )
    for filename, notice in report.notices:
        rows.append((filename, "0", "guard-notice", collapse_ws(notice), "", ""))

    def sort_key(row: tuple[str, ...]) -> tuple:
        return (row[2] != "extension-unavailable", row[0], int(row[1]))

    rows.sort(key=sort_key)
    body = "\n".join("\t".join(col.replace("\t", " ") for col in row) for row in rows)
    stats = (
        f"# upstream repo: {pin['repo']}\n"
        f"# upstream commit: {pin['commit']}\n"
        f"# applied: {len(report.applied)} migration files, {report.statements} statements\n"
        f"# skipped: {len(report.skipped)} statement(s), {len(report.notices)} guard notice(s)\n"
        "#\n"
    )
    return TSV_TITLE + stats + TSV_COLUMNS + body + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--migrations", default=DEFAULT_MIGRATIONS, help="vendored upstream .up.sql dir")
    ap.add_argument("--manifest", default=DEFAULT_MANIFEST, help="sha256 manifest to verify first")
    ap.add_argument("--pin", default=DEFAULT_PIN, help="PIN file with the upstream commit")
    ap.add_argument("--out-sql", default=DEFAULT_OUT_SQL)
    ap.add_argument("--out-json", default=DEFAULT_OUT_JSON)
    ap.add_argument("--out-exceptions", default=DEFAULT_OUT_EXCEPTIONS)
    ap.add_argument(
        "--db-url",
        default=os.environ.get("MULTICA_TEST_DATABASE_URL", ""),
        help="postgres:// URL of an existing database on the target server "
        "(default: $MULTICA_TEST_DATABASE_URL)",
    )
    ap.add_argument("--db-name", default=DEFAULT_DB_NAME, help="scratch database to build in")
    ap.add_argument("--keep-db", action="store_true", help="do not drop the scratch database")
    ap.add_argument(
        "--lenient",
        action="store_true",
        help="record an unexpected statement failure and carry on instead of failing",
    )
    ap.add_argument(
        "--skip-manifest-check",
        action="store_true",
        help="do not verify MANIFEST.sha256 (only for debugging the snapshot itself)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="rebuild in a scratch database and diff against the checked-in files; write nothing",
    )
    ap.add_argument("--json", action="store_true", help="machine-readable summary on stdout")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    def say(message: str) -> None:
        if not args.quiet and not args.json:
            print(message, file=sys.stderr)

    try:
        migrations = (ROOT / args.migrations).resolve()
        if not migrations.is_dir():
            raise SchemaToolError(f"{migrations} is not a directory")
        files = sorted(migrations.glob("*.up.sql"), key=lambda p: p.name)
        required_exts: set[str] = set()
        if not files:
            raise SchemaToolError(f"{migrations} contains no *.up.sql")
        pin = read_pin(ROOT / args.pin)
        declared = pin.get("up_files", "")
        if declared and declared.isdigit() and int(declared) != len(files):
            raise SchemaToolError(
                f"{args.pin} says up_files: {declared} but {len(files)} are vendored"
            )

        # Replay order is byte-wise file-name order (`ls *.up.sql`, LC_ALL=C), which is also
        # the order upstream's embedded-FS directory listing yields.  Upstream *does* reuse
        # numbers: e.g. `029_attachment`, `029_daemon_token` and `029_drop_daemon_pairing` all
        # exist, so the tie-break inside a number is the alphabetical suffix, and a dependency
        # between two files sharing a number would be order-fragile upstream too.  We therefore
        # do not renumber anything (the vendored bytes stay untouched) — we assert that the
        # prefixes are zero-padded so alphabetical order equals numeric order, and count the
        # shared numbers so the number is visible in every run instead of being folklore.
        unpadded = [p.name for p in files if not re.match(r"^\d{3}_", p.name)]
        if unpadded:
            raise SchemaToolError(
                "vendored migrations must be named `<3-digit number>_<name>.up.sql` so that "
                f"alphabetical order is numeric order; these are not: {unpadded[:5]}"
            )
        numbers = [migration_number(p.name) for p in files]
        shared_numbers = sorted({n for n in numbers if numbers.count(n) > 1})
        for path in files:
            for ext in required_extensions(path.read_text(encoding="utf-8")):
                assert_extension_markers_cover({ext})
                required_exts.add(ext)

        if args.skip_manifest_check:
            say("warning: skipping MANIFEST.sha256 verification")
            verified = 0
        else:
            verified = verify_manifest(ROOT / args.manifest, migrations, files)

        db_url = parse_db_url(args.db_url)
        with ScratchDatabase(db_url, args.db_name, keep=args.keep_db) as db:
            available = db.available_extensions()
            say(
                f"replaying {len(files)} migrations into {args.db_name} "
                f"({database_name(db_url)} @ {redact(db_url).rsplit('@', 1)[-1]})"
            )
            report = apply_migrations(db, files, available=available, strict=not args.lenient)
            snapshot = build_snapshot(
                db,
                label="upstream",
                source=(
                    f"{pin['repo']} @ {pin['commit']} — `{' '.join(args.migrations.split('/'))}`"
                    f"/*.up.sql"
                ),
                meta={
                    "upstream_repo": pin["repo"],
                    "upstream_commit": pin["commit"],
                    "migrations_applied": len(report.applied),
                    "migration_numbers": len(set(numbers)),
                    "shared_migration_numbers": shared_numbers,
                    "apply_order": "byte-wise file-name order (LC_ALL=C)",
                    "statements_applied": report.statements - len(report.skipped),
                    "statements_skipped": len(report.skipped),
                    "manifest_verified_files": verified,
                    "generated_by": GENERATED_BY,
                },
            )
            dump = normalize_dump(db.pg_dump_schema())
            server_version = snapshot["meta"]["server_version"]
            ext_versions = ", ".join(
                f"{name} {installed}"
                for name, _default, installed in db.query(
                    "SELECT name, default_version, installed_version FROM pg_available_extensions "
                    "WHERE installed_version IS NOT NULL ORDER BY name"
                )
            )

        counts: dict[str, int] = {}
        for obj in snapshot["objects"]:
            counts[obj["kind"]] = counts.get(obj["kind"], 0) + 1
        skipped_objects = report.objects_skipped()
        missing_extensions = sorted(required_exts - available)

        header = snapshot_header(
            repo=pin["repo"],
            commit=pin["commit"],
            generated_by=GENERATED_BY,
            extra=[
                f"upstream commit  : {pin['commit']}",
                f"postgres server  : {server_version}",
                f"migrations       : {len(report.applied)} applied, {report.statements} statements",
                f"numbers          : {len(set(numbers))} distinct numbers, {len(shared_numbers)} "
                "shared by more than one file (order inside a number: alphabetical)",
                f"recorded skips   : {len(report.skipped)} statement(s) — see "
                "contracts/upstream-apply-exceptions.tsv",
                f"extensions       : {ext_versions or '(none)'}",
                "missing ext      : "
                + (
                    f"{', '.join(missing_extensions)} — absent from this snapshot, registered in "
                    "contracts/schema-deviations.tsv"
                    if missing_extensions
                    else "(none)"
                ),
                "live objects     : " + ", ".join(f"{k} {counts[k]}" for k in sorted(counts)),
                "note             : the snapshot is the upstream schema *as reproducible here*; "
                "objects only pg_bigm/pg_cron can create are absent and registered instead",
            ],
        )
        sql_text = header + dump

        drift: list[str] = []
        if args.check:
            for path, text in (
                (ROOT / args.out_sql, sql_text),
                (
                    ROOT / args.out_json,
                    json.dumps(snapshot, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
                ),
                (ROOT / args.out_exceptions, render_exceptions(report, pin)),
            ):
                if not path.exists():
                    drift.append(f"{path.relative_to(ROOT)}: missing")
                elif path.read_text(encoding="utf-8") != text:
                    drift.append(f"{path.relative_to(ROOT)}: differs")
        else:
            write_text(ROOT / args.out_sql, sql_text)
            write_text(
                ROOT / args.out_json,
                json.dumps(snapshot, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            )
            write_text(ROOT / args.out_exceptions, render_exceptions(report, pin))

        summary = {
            "ok": not report.unexpected and not drift,
            "mode": "check" if args.check else "write",
            "upstream_commit": pin["commit"],
            "server_version": server_version,
            "migrations": len(report.applied),
            "migration_numbers": len(set(numbers)),
            "shared_migration_numbers": shared_numbers,
            "statements": report.statements,
            "skipped": len(report.skipped),
            "unexpected_skips": [f"{s.file}:{s.line}: {s.reason}" for s in report.unexpected],
            "guard_notices": len(report.notices),
            "skipped_objects": [f"{kind}:{name}" for kind, name in sorted(skipped_objects)],
            "missing_extensions": missing_extensions,
            "required_extensions": sorted(required_exts),
            "objects": counts,
            "extensions": snapshot["meta"]["extensions"],
            "check_differences": drift,
            "snapshot_format": SNAPSHOT_FORMAT,
            "outputs": {
                "sql": str(args.out_sql),
                "json": str(args.out_json),
                "exceptions": str(args.out_exceptions),
            },
        }

        if args.json:
            print(json.dumps(summary, ensure_ascii=False, indent=2))
        elif not args.quiet:
            print(
                f"{'check' if args.check else 'wrote'}: {sum(counts.values())} objects "
                f"({', '.join(f'{k} {counts[k]}' for k in sorted(counts))}), "
                f"{len(report.skipped)} skip(s), {len(report.notices)} guard notice(s)"
            )
            if drift:
                print("snapshot out of date: " + "; ".join(drift))
        return 0 if not report.unexpected and not drift else 1
    except SchemaToolError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    try:
        _code = main()
        sys.stdout.flush()
    except BrokenPipeError:
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, sys.stdout.fileno())
        _code = 0
    raise SystemExit(_code)
