#!/usr/bin/env python3
"""Generate `docs/fixtures/upstream-routes.tsv` from upstream multica's router.go.

Why this script exists
----------------------
`scripts/route_parity.py` compares the routes this repo implements against the
routes upstream multica serves.  The upstream half of that comparison is a
checked-in snapshot (`docs/fixtures/upstream-routes.tsv`) so the parity check is
hermetic: no network, no upstream checkout required.

The snapshot has to be regenerated whenever upstream `main` moves.  Doing that
by hand is exactly the kind of manual step this tooling slice exists to remove,
so the snapshot is generated by this script.  The script is *idempotent with
respect to the hand-maintained `owner` column*: re-running it preserves existing
ownership annotations and only adds/removes route rows.

Input
-----
A local checkout of upstream `louloulin/multica`.  The clone recipe (full-blob
shallow clone, ~5s) is `docs/20-UPSTREAM-ANALYSIS-RECIPE.md` §1:

    git clone --depth 1 --single-branch --branch main \\
        https://github.com/louloulin/multica <dir>

Do **not** grep a `git init` + `--filter=blob:none` "blobby" repository: that
combination deadlocks for ~74 minutes per grep (docs/20 §2-§4).

Usage
-----
    python3 scripts/gen_upstream_routes.py \\
        --router ../multica/server/cmd/server/router.go \\
        --const-file ../multica/server/pkg/publicapi/v1/routes.go \\
        --out docs/fixtures/upstream-routes.tsv \\
        --commit f41fae6b08fb734afcbd13205c0b3203dd0bc9c6

`--commit` is recorded in the fixture header; it is not read from the checkout
so the recorded sha is always an explicit, reviewable input.  `--check`
re-renders in memory and fails if the checked-in fixture differs (CI-friendly).

Parsing notes / limitations
---------------------------
* The upstream router is chi v5.  Nesting is expressed with
  `r.Route("<prefix>", func(r chi.Router) { ... })`, `r.Group(func(r chi.Router) { ... })`
  and middleware chains (`r.With(mw).Get(...)`); prefixes are concatenated.
* chi's `Mount` is not used by `router.go` (verified: `grep -n '\\.Mount(' ` is
  empty), so no mounted-handler resolution is needed.  If a future upstream
  revision starts using `Mount`, this script aborts loudly rather than silently
  dropping routes.
* Route groups that live in helper functions taking a `chi.Router` (currently
  only `registerPluginActionRoutes`) are inlined at the current prefix, because
  that is how upstream calls them (`r.Route(prefix, func(...) { register... })`).
* `{param}` names are kept verbatim.  `scripts/route_parity.py` normalises
  `{x}`/`:x` when comparing the two sides.
* chi serves both `/api/inbox` and `/api/inbox/` for `r.Route("/api/inbox", ...)`
  plus `r.Get("/", ...)`.  The fixture keeps the literal zero-slash form chi
  registers (`/api/inbox/`); the parity script strips one trailing slash before
  comparing.  Do not "fix" this here: the fixture must stay a faithful record of
  what chi registers.
* A route path that is not a string literal (e.g. `publicapiv1.BasePath`) is
  resolved from constants declared in the router file itself or in a
  `--const-file`.  Anything still unresolved aborts: a guessed path would
  corrupt the fixture.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import OrderedDict

HTTP_METHODS = {
    "Get": "GET",
    "Post": "POST",
    "Put": "PUT",
    "Patch": "PATCH",
    "Delete": "DELETE",
    "Head": "HEAD",
    "Options": "OPTIONS",
    "Connect": "CONNECT",
    "Trace": "TRACE",
}

# Calls that look like route registration but install middleware, or that this
# generator deliberately does not support.  `With`/`Use` are handled by the
# chain resolver (the meaningful call is whatever they are chained to).
IGNORED_CALLS = {"Use", "NotFound", "MethodNotAllowed", "ServeHTTP", "HandleFunc"}

FIXTURE_COLUMNS = ("method", "path", "owner")


class RouteParseError(RuntimeError):
    """Raised when the upstream router shape is not what this parser expects."""


# --------------------------------------------------------------------------- #
# lexing helpers
# --------------------------------------------------------------------------- #


def mask_literals_and_comments(src: str) -> tuple[str, list[tuple[int, int, str]]]:
    """Blank out string bodies and comments, keeping byte offsets stable.

    Returns the masked source plus every string literal as
    `(start, end, value)`, where `[start, end)` spans the literal *including*
    its quotes.  The masked copy has the same length as the input, so a regex
    match offset is valid in both.
    """
    out = list(src)
    literals: list[tuple[int, int, str]] = []
    i = 0
    n = len(src)
    while i < n:
        c = src[i]
        if c == "/" and i + 1 < n and src[i + 1] == "/":
            j = src.find("\n", i)
            j = n if j < 0 else j
            for k in range(i, j):
                out[k] = " "
            i = j
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "*":
            j = src.find("*/", i)
            j = n if j < 0 else j + 2
            for k in range(i, j):
                out[k] = " "
            i = j
            continue
        if c == "`":
            j = src.find("`", i + 1)
            j = n if j < 0 else j
            literals.append((i, j + 1, src[i + 1 : j]))
            for k in range(i + 1, j):
                out[k] = " "
            i = j + 1
            continue
        if c in "\"'":
            j = i + 1
            while j < n:
                if src[j] == "\\":
                    j += 2
                    continue
                if src[j] == c:
                    break
                j += 1
            literals.append((i, j + 1, src[i + 1 : j]))
            for k in range(i + 1, j):
                out[k] = " "
            i = j + 1
            continue
        i += 1
    return "".join(out), literals


def matching_brace(masked: str, open_idx: int) -> int:
    """Index one past the bracket that closes the one at `open_idx`."""
    depth = 0
    i = open_idx
    n = len(masked)
    while i < n:
        c = masked[i]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise RouteParseError(f"unbalanced brackets at offset {open_idx}")


CALL_HEAD = re.compile(r"\.\s*([A-Za-z_]\w*)\s*\(")


def resolve_chain(
    masked: str, dot_idx: int
) -> tuple[list[str], list[tuple[int, int]], int]:
    """Resolve `.With(mw).Get("/x", h)` starting at the leading dot.

    Returns `(names, arg_spans, end)`: `names[i]` is the i-th chained method and
    `arg_spans[i]` is the *inside* of its argument list.
    """
    names: list[str] = []
    spans: list[tuple[int, int]] = []
    i = dot_idx
    while True:
        m = CALL_HEAD.match(masked, i)
        if not m:
            break
        names.append(m.group(1))
        open_idx = m.end() - 1
        close_idx = matching_brace(masked, open_idx)
        spans.append((open_idx + 1, close_idx - 1))
        end = close_idx
        nxt = re.compile(r"\s*\.\s*[A-Za-z_]\w*\s*\(").match(masked, end)
        if not nxt:
            return names, spans, end
        i = end + nxt.group(0).index(".")
        continue
    raise RouteParseError(f"unparsable call chain at offset {dot_idx}")


def literal_at(
    masked: str, literals: list[tuple[int, int, str]], pos: int
) -> str | None:
    """Value of the string literal that starts exactly at `pos`, if any."""
    for start, _end, value in literals:
        if start == pos:
            return value
        if start > pos:
            break
    return None


def first_arg_span_offsets(span: tuple[int, int], masked: str) -> tuple[int, int]:
    """`(start, comma_or_end)` of the first argument inside `span`."""
    start, end = span
    body = masked[start:end]
    depth = 0
    for idx, c in enumerate(body):
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == "," and depth == 0:
            return start, start + idx
    return start, end


def join_path(prefix: str, path: str) -> str:
    """chi concatenation semantics for nested `Route` prefixes."""
    if not prefix:
        return path
    if not path:
        return prefix
    if path.startswith("/"):
        return prefix.rstrip("/") + path
    return prefix.rstrip("/") + "/" + path


# --------------------------------------------------------------------------- #
# route extraction
# --------------------------------------------------------------------------- #


class RouterParser:
    def __init__(self, src: str, const_files: list[str] | None = None, overrides=None) -> None:
        self.src = src
        self.masked, self.literals = mask_literals_and_comments(src)
        self.overrides = dict(overrides or {})
        self.const_values: dict[str, str] = {}
        for path in [None] + list(const_files or []):
            text = src if path is None else _read(path)
            for name, value in parse_string_consts(text).items():
                self.const_values.setdefault(name, value)

    # -- entry points -------------------------------------------------------- #

    def function_bodies(self) -> list[tuple[str, int, int]]:
        """Top-level `func` bodies as `(name, body_open, body_close)`."""
        out: list[tuple[str, int, int]] = []
        for m in re.finditer(
            r"^func\s+(?:\([^)]*\)\s*)?([A-Za-z_]\w*)\s*\(", self.src, re.MULTILINE
        ):
            paren = self.masked.index("(", m.start())
            close = matching_brace(self.masked, paren)
            brace = self.masked.find("{", close)
            if brace < 0:
                continue
            out.append((m.group(1), brace + 1, matching_brace(self.masked, brace) - 1))
        return out

    def declare_helpers(self) -> dict[str, tuple[int, int]]:
        """Functions that register routes on a `chi.Router` parameter."""
        helpers: dict[str, tuple[int, int]] = {}
        bodies = {name: (o, c) for name, o, c in self.function_bodies()}
        for m in re.finditer(
            r"^func\s+([A-Za-z_]\w*)\s*\([^)]*chi\.Router", self.src, re.MULTILINE
        ):
            if m.group(1) in bodies:
                helpers[m.group(1)] = bodies[m.group(1)]
        return helpers

    # -- path expressions ---------------------------------------------------- #

    def resolve_path(self, span: tuple[int, int]) -> str:
        start, end = first_arg_span_offsets(span, self.masked)
        expr = self.masked[start:end].strip()
        if not expr:
            raise RouteParseError(f"empty route path argument at offset {start}")
        if expr[0] in "\"`":
            value = literal_at(self.masked, self.literals, start + self.masked[start:end].index(expr[0]))
            if value is None:
                raise RouteParseError(f"unreadable string literal {expr!r} at offset {start}")
            return value
        if expr in self.overrides:
            return self.overrides[expr]
        name = expr.split(".")[-1]
        if name in self.const_values:
            return self.const_values[name]
        raise RouteParseError(
            f"cannot resolve route path expression {expr!r}; declare it in a "
            f"--const-file or pass --const {expr}=/value explicitly"
        )

    # -- walking ------------------------------------------------------------- #

    def walk(
        self,
        start: int,
        end: int,
        prefix: str,
        helpers: dict[str, tuple[int, int]],
        found: "OrderedDict[tuple[str, str], list[int]]",
        inlined: list[str],
    ) -> None:
        helper_re = (
            re.compile(r"(?<![\w.])(?:%s)\s*\(" % "|".join(map(re.escape, helpers)))
            if helpers
            else None
        )
        i = start
        while i < end:
            call = CALL_HEAD.search(self.masked, i, end)
            bare = helper_re.search(self.masked, i, end) if helper_re else None
            if bare and (call is None or bare.start() < call.start()) and bare.start() < end:
                name = bare.group(0)[: bare.group(0).index("(")].strip()
                open_idx = bare.end() - 1
                call_end = matching_brace(self.masked, open_idx)
                if name not in inlined:
                    h_open, h_close = helpers[name]
                    self.walk(h_open, h_close, prefix, helpers, found, inlined + [name])
                i = call_end
                continue
            if call is None or call.start() >= end:
                break
            names, spans, call_end = resolve_chain(self.masked, call.start())
            i = call_end
            last = names[-1]
            if last in HTTP_METHODS:
                path = self.resolve_path(spans[-1])
                found.setdefault(
                    (HTTP_METHODS[last], join_path(prefix, path)), []
                ).append(self.line_of(call.start()))
            elif last == "Route":
                path = self.resolve_path(spans[-1])
                block = self.func_block_in(spans[-1])
                if block is None:
                    raise RouteParseError(
                        f"Route(...) at line {self.line_of(call.start())} has no func block"
                    )
                self.walk(
                    block[0], block[1], join_path(prefix, path), helpers, found, inlined
                )
            elif last == "Group":
                block = self.func_block_in(spans[-1])
                if block is None:
                    raise RouteParseError(
                        f"Group(...) at line {self.line_of(call.start())} has no func block"
                    )
                self.walk(block[0], block[1], prefix, helpers, found, inlined)
            elif "Mount" in names:
                raise RouteParseError(
                    "upstream router.go uses chi Mount; this generator cannot resolve "
                    "mounted handlers — extend it rather than dropping routes"
                )
            elif last in IGNORED_CALLS or last == "With":
                continue
            # any other chained call is a custom handler: no path, ignore
        return

    def func_block_in(self, span: tuple[int, int]) -> tuple[int, int] | None:
        start, end = span
        m = re.search(r"\bfunc\b", self.masked[start:end])
        if not m:
            return None
        brace = self.masked.find("{", start + m.end())
        if brace < 0 or brace >= end:
            return None
        return brace + 1, matching_brace(self.masked, brace) - 1

    def line_of(self, offset: int) -> int:
        return self.src.count("\n", 0, offset) + 1

    def extract(self) -> list[tuple[str, str, int]]:
        helpers = self.declare_helpers()
        candidates = [
            (name, o, c)
            for name, o, c in self.function_bodies()
            if name not in helpers and name.startswith("NewRouter")
        ]
        if not candidates:
            raise RouteParseError("no NewRouter*/NewRouterWithOptions body found")
        scored = sorted(
            (
                len(re.findall(r"\.(?:Get|Post|Put|Patch|Delete|Route)\s*\(", self.masked[o:c])),
                name,
                o,
                c,
            )
            for name, o, c in candidates
        )
        _score, entry, o, c = scored[-1]
        if _score == 0:
            raise RouteParseError(f"entry function {entry} registers no routes")
        found: "OrderedDict[tuple[str, str], list[int]]" = OrderedDict()
        self.walk(o, c, "", helpers, found, [])
        routes = [(method, path, lines[0]) for (method, path), lines in found.items()]
        routes.sort(key=lambda r: (r[1], r[0]))
        return routes


def _read(path: str) -> str:
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def parse_string_consts(src: str) -> dict[str, str]:
    """`Name = "value"` declarations (file-level or inside a const block)."""
    masked, literals = mask_literals_and_comments(src)
    consts: dict[str, str] = {}
    for m in re.finditer(
        r"(?:^|[({;,]|\bconst\b)\s*([A-Za-z_]\w*)\s*=\s*[\"`]", src, re.MULTILINE
    ):
        value = literal_at(masked, literals, m.end() - 1)
        if value is None:
            continue
        consts.setdefault(m.group(1), value)
    return consts


# --------------------------------------------------------------------------- #
# fixture IO
# --------------------------------------------------------------------------- #


def read_owners(path: str) -> dict[tuple[str, str], str]:
    """Existing `(method, path) -> owner` annotations, for regeneration."""
    owners: dict[tuple[str, str], str] = {}
    try:
        lines = _read(path).splitlines()
    except FileNotFoundError:
        return owners
    for line in lines:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2 or parts[0].strip().lower() == "method":
            continue
        owners[(parts[0].strip(), parts[1].strip())] = (
            parts[2].strip() if len(parts) > 2 else ""
        )
    return owners


def read_owner_rules(path: str | None) -> list[tuple[re.Pattern[str], str]]:
    """Ordered `(regex, owner)` seeding rules, first match wins.

    Rules only ever *fill in* an empty owner — a route that already carries an
    explicit owner in the fixture keeps it, so every reassignment shows up as a
    reviewable fixture diff instead of being silently reapplied.
    """
    if not path:
        return []
    rules: list[tuple[re.Pattern[str], str]] = []
    for lineno, line in enumerate(_read(path).splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            raise RouteParseError(
                f"{path}:{lineno}: expected `regex<TAB>owner<TAB>rationale`"
            )
        pattern, owner = parts[0], parts[1].strip()
        try:
            rules.append((re.compile(pattern), owner))
        except re.error as exc:
            raise RouteParseError(f"{path}:{lineno}: bad regex {pattern!r}: {exc}") from exc
    return rules


def rule_owner(rules: list[tuple[re.Pattern[str], str]], path: str) -> str:
    for pattern, owner in rules:
        if pattern.search(path):
            return owner
    return ""


def render_fixture(
    routes: list[tuple[str, str, int]],
    owners: dict[tuple[str, str], str],
    owner_rules: list[tuple[re.Pattern[str], str]],
    commit: str,
    source_url: str,
    command: str,
) -> str:
    out = [
        "# upstream-routes.tsv — upstream multica HTTP route table (method, path, owner).",
        "#",
        "# Consumed by scripts/route_parity.py. Never fetched over the network.",
        f"# source: {source_url} :: server/cmd/server/router.go",
        f"# upstream commit: {commit}",
        "# clone recipe: docs/20-UPSTREAM-ANALYSIS-RECIPE.md §1 (full-blob shallow clone, ~5s)",
        f"# regenerate: {command}",
        "#",
        "# owner column = which milestone/sub-issue owns porting this route into multica-rs.",
        "#   vocabulary: M1 / M2-A..M2-E / M3..M10 / M3+ (deferred past M3, no issue yet)",
        "#   / n/a (deliberately not ported).  Rationale table: docs/22-ROUTE-PARITY.md.",
        "#   An EMPTY owner on a not-yet-implemented route is an unclaimed blind spot:",
        "#   `python3 scripts/route_parity.py` fails (exit 1) on it.",
        "# Regeneration preserves this column; never reorder or drop it by hand.",
        "#",
        "# columns: " + "\\t".join(FIXTURE_COLUMNS),
    ]
    for method, path, line in routes:
        owner = owners.get((method, path), "") or rule_owner(owner_rules, path)
        out.append(f"{method}\t{path}\t{owner}\t# router.go:{line}")
    return "\n".join(out) + "\n"


def build_command(args: argparse.Namespace) -> str:
    parts = [
        "python3 scripts/gen_upstream_routes.py",
        f"--router {args.router}",
    ]
    for path in args.const_file:
        parts.append(f"--const-file {path}")
    if args.owner_rules:
        parts.append(f"--owner-rules {args.owner_rules}")
    parts += [f"--out {args.out}", f"--commit {args.commit}"]
    return " ".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate the upstream route fixture from router.go",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--router", required=True, help="upstream server/cmd/server/router.go")
    ap.add_argument("--out", required=True, help="fixture path to write")
    ap.add_argument("--commit", required=True, help="upstream commit sha of the checkout")
    ap.add_argument(
        "--const-file",
        action="append",
        default=[],
        metavar="PATH",
        help="Go file whose string consts resolve route path expressions (repeatable)",
    )
    ap.add_argument(
        "--const",
        action="append",
        default=[],
        metavar="EXPR=VALUE",
        help="resolve a specific non-literal route path expression (repeatable)",
    )
    ap.add_argument(
        "--owner-rules",
        default=None,
        metavar="PATH",
        help="TSV of `regex<TAB>owner<TAB>rationale` used to seed EMPTY owner cells",
    )
    ap.add_argument(
        "--source-url",
        default="https://github.com/louloulin/multica",
        help="upstream repository URL recorded in the header",
    )
    ap.add_argument(
        "--check", action="store_true", help="do not write; exit 1 if the fixture is stale"
    )
    args = ap.parse_args(argv)

    overrides: dict[str, str] = {}
    for item in args.const:
        if "=" not in item:
            ap.error(f"--const expects EXPR=VALUE, got {item!r}")
        expr, value = item.split("=", 1)
        overrides[expr.strip()] = value

    try:
        parser = RouterParser(_read(args.router), args.const_file, overrides)
        routes = parser.extract()
        owner_rules = read_owner_rules(args.owner_rules)
    except RouteParseError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    owners = read_owners(args.out)
    rendered = render_fixture(
        routes, owners, owner_rules, args.commit, args.source_url, build_command(args)
    )

    if args.check:
        try:
            current = _read(args.out)
        except FileNotFoundError:
            print(f"error: {args.out} does not exist", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"error: {args.out} is out of date — regenerate with the header command",
                file=sys.stderr,
            )
            return 1
        print(f"{args.out} is up to date ({len(routes)} routes)")
        return 0

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    unowned = [
        f"{m} {p}"
        for m, p, _l in routes
        if not (owners.get((m, p), "") or rule_owner(owner_rules, p))
    ]
    print(f"wrote {args.out}: {len(routes)} routes ({len(unowned)} without an owner)")
    if unowned:
        shown = "\n".join(f"  {r}" for r in unowned[:20])
        print(
            f"note: route_parity.py will report these as unclaimed:\n{shown}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
