#!/usr/bin/env python3
"""schema_drift.py — plan1 D1 的红灯：本仓迁移到的 schema 还是不是 vendored 的上游 schema？

It applies the migrations **this repo actually applies** (`migrations/**.up.sql` — the vendored
`upstream/` files and this repo's `compat/` patches, merged by file stem) to a throwaway
database, snapshots the result with the *same* extractor the other side used
(`scripts/schema_snapshot.py`), and diffs that snapshot against
`contracts/upstream-schema.json`.  Exit 0 means *every* difference is registered in
`contracts/schema-deviations.tsv`, with a reason and the issue that will close it.  Why it
exists (the D1 failure it kills), the normalisation rules and the recorded counts live in
`docs/25-W0-SCHEMA-DRIFT.md`.

Differences come in four categories — `missing` / `extra` / `differs` / `apply-exception`, see
docs/25 §4.2.  A `differs:` difference is reported per object; the columns, constraints,
indexes and triggers owned by a missing or extra *table* are folded into that table's row
instead of being listed one by one.  `apply-exception:` rows are not measured here at all: they
mirror the generated `contracts/upstream-apply-exceptions.tsv` (snapshots of this machine
cannot contain objects whose statement needs `pg_bigm` / `pg_cron`), so a skip with no
registered row fails and a registered row with no skip fails too.

Registry rows are TSV, `#` comments allowed: `对象 / 类型 / 差异摘要 / 原因 / 承接 issue`.
`对象` is an exact object key or a glob (`<table>.*` in practice) and `差异摘要` starts with one
of the four categories; `原因` and `承接 issue` are mandatory — `--emit-deviations` prints
skeleton rows with those two columns *empty*, so pasting its output back can never satisfy the
check.  A row that matches no difference is stale: a warning for most categories, a hard error
for `apply-exception:`, whose rows are generated and must stay in lockstep with the exceptions
file.  The report prints how many differences each row covers.

Usage
-----
    export MULTICA_TEST_DATABASE_URL=postgres://user:pw@127.0.0.1:5432/multica_test
    python3 scripts/schema_drift.py                        # human report, exit 0/1/2
    python3 scripts/schema_drift.py --json                 # machine report
    python3 scripts/schema_drift.py --quiet                # exit code only (CI)
    python3 scripts/schema_drift.py --emit-deviations      # skeleton registry rows

    # W0-B2 exploration: the vendored upstream files alone, without this repo's
    # `migrations/compat/` patches — shows the raw gap the patches close
    python3 scripts/schema_drift.py --apply-set upstream

Exit codes
----------
    0   every difference is registered (no output under `--quiet`)
    1   drift is not fully registered, a skip is unregistered, an `apply-exception:` row is
        stale, or a migration failed unexpectedly
    2   usage / environment / parse error (no URL, no server, malformed snapshot, registry
        or exceptions file, missing files) — the check did not run, so it is not a pass

`--apply-set local` (the default) is the CI mode: exactly the set the runtime applies — every
`*.up.sql` under `migrations/`, recursively, keyed and ordered by file stem, so the vendored
`upstream/` files and this repo's `compat/` patches form one numbering space (duplicate stems
are rejected, matching `mc_db::Migrator::load_dirs`).  `--apply-set upstream` applies the
vendored upstream files alone, with no compat patches, and is lenient about extension-gated
statements — it shows what the patches are for, so it is an aid, not a gate.

Nothing here is regenerated by CI: the snapshots are inputs and this script only reads them.
It never writes to the repo and never touches the network.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))  # scripts/ is not a package

from schema_snapshot import (  # noqa: E402  (path juggling is deliberate)
    SNAPSHOT_FORMAT,
    ScratchDatabase,
    SchemaToolError,
    apply_migrations,
    build_snapshot,
    collapse_ws,
    parse_db_url,
    sha256_of,
    skip_object_keys,
)

ROOT = Path(__file__).resolve().parent.parent

DEFAULT_DB_NAME = "schema_probe_w0b_drift"
DEFAULT_MIGRATIONS = "migrations"
DEFAULT_UPSTREAM_MIGRATIONS = "migrations/upstream"
DEFAULT_UPSTREAM_SCHEMA = "contracts/upstream-schema.json"
DEFAULT_DEVIATIONS = "contracts/schema-deviations.tsv"
DEFAULT_EXCEPTIONS = "contracts/upstream-apply-exceptions.tsv"

DEVIATION_COLUMNS = ("对象", "类型", "差异摘要", "原因", "承接 issue")
CATEGORIES = ("missing", "extra", "differs", "apply-exception")
#: kinds that hang off a table: folded into their table's row when that table itself is
#: missing/extra, compared object by object otherwise.
CHILD_KINDS = ("column", "constraint", "index", "trigger")

#: the registry's own header.  `contracts/schema-deviations.tsv` is written once with
#: `python3 -c 'import sys; sys.path.insert(0, "scripts"); import schema_drift as s;
#: print(s.TSV_PREAMBLE + s.TSV_COLUMNS, end="")' > contracts/schema-deviations.tsv`
#: and then filled in by hand.
TSV_PREAMBLE = (
    "# contracts/schema-deviations.tsv — every difference between this repo's schema and\n"
    "# contracts/upstream-schema.json, registered with a reason and the issue that closes it.\n"
    "#\n"
    "# scripts/schema_drift.py exits 0 only when every difference it finds is registered here.\n"
    "# Columns (tab separated):\n"
    "#   对象         an object key, or a glob such as `issue.*` for one table's columns\n"
    "#   类型         table | column | constraint | index | function | trigger | type | view |\n"
    "#                extension | statement\n"
    "#   差异摘要     `missing:`, `extra:`, `differs:` or `apply-exception:` followed by what was\n"
    "#                compared; the tool checks the prefix and reports the rest verbatim\n"
    "#   原因         why the difference is acceptable — not what it looks like\n"
    "#   承接 issue   the issue that must close it; `W0-B2` is the plan1 P4 slice that switches the\n"
    "#                runtime to the vendored upstream migration set\n"
    "#\n"
    "# 原因 and 承接 issue are mandatory and must be filled in by a person.  The skeleton rows from\n"
    "# `scripts/schema_drift.py --emit-deviations` leave them blank on purpose, so pasting that\n"
    "# output back can never satisfy the check.\n"
    "#\n"
    "# apply-exception rows are not hand-measured at all: they mirror\n"
    "# contracts/upstream-apply-exceptions.tsv (generated, one row per skipped statement).  A row\n"
    "# of that category with no matching skip, or a skip with no row, fails the check.\n"
)
TSV_COLUMNS = "# 对象\t类型\t差异摘要\t原因\t承接 issue\n"


# --------------------------------------------------------------------------- #
# loading the three inputs
# --------------------------------------------------------------------------- #


def load_snapshot(path: Path) -> dict:
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SchemaToolError(
            f"{path} is missing — build it with scripts/build_upstream_schema.py (see "
            "docs/25-W0-SCHEMA-DRIFT.md §3).  CI only reads it; it never regenerates it."
        )
    except json.JSONDecodeError as exc:
        raise SchemaToolError(f"{path} is not valid JSON: {exc}") from None
    if doc.get("format") != SNAPSHOT_FORMAT:
        raise SchemaToolError(
            f"{path}: snapshot format {doc.get('format')!r} is not the expected {SNAPSHOT_FORMAT} — "
            "the extractor changed; rebuild the snapshot deliberately instead of diffing across it"
        )
    if not doc.get("objects"):
        raise SchemaToolError(f"{path}: the snapshot has no objects — refusing to diff against nothing")
    for obj in doc["objects"]:
        if "kind" not in obj or "key" not in obj:
            raise SchemaToolError(f"{path}: malformed object row: {obj!r}")
    return doc


def object_map(snapshot: dict) -> dict[tuple[str, str], dict]:
    """`{(kind, key): definition}` from a snapshot document."""
    return {(o["kind"], o["key"]): o.get("def", {}) for o in snapshot["objects"]}


@dataclass
class DeviationRow:
    """One registered difference: `contracts/schema-deviations.tsv`."""

    key: str
    kind: str
    summary: str
    reason: str
    issue: str
    line: int
    covered: int = 0
    example: str = ""

    @property
    def category(self) -> str:
        return self.summary.split(":", 1)[0].strip()

    def matches(self, item: "DiffItem") -> bool:
        if self.kind not in (item.kind, "*") or self.category != item.category:
            return False
        return self.key == item.key or fnmatch(item.key, self.key)


def load_deviations(path: Path, *, allow_missing: bool = False) -> list[DeviationRow]:
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        if allow_missing:
            return []
        raise SchemaToolError(
            f"{path} is missing — create it (header: see TSV_PREAMBLE in this script, rows: "
            "`python3 scripts/schema_drift.py --emit-deviations`) before gating CI on this check"
        ) from None
    rows: list[DeviationRow] = []
    for lineno, line in enumerate(raw.splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = [p.strip() for p in line.split("\t")]
        if len(parts) != len(DEVIATION_COLUMNS):
            raise SchemaToolError(
                f"{path}:{lineno}: expected {len(DEVIATION_COLUMNS)} tab-separated columns "
                f"({', '.join(DEVIATION_COLUMNS)}), found {len(parts)}: {line[:80]!r}"
            )
        key, kind, summary, reason, issue = parts
        if not key or not kind or not summary:
            raise SchemaToolError(f"{path}:{lineno}: 对象, 类型 and 差异摘要 must not be empty")
        category = summary.split(":", 1)[0].strip()
        if category not in CATEGORIES:
            raise SchemaToolError(
                f"{path}:{lineno}: 差异摘要 must start with one of {', '.join(CATEGORIES)}, "
                f"found {category!r}"
            )
        if not reason:
            raise SchemaToolError(
                f"{path}:{lineno}: 原因 is empty — a registered difference needs a reason a "
                "reviewer can disagree with"
            )
        if not issue:
            raise SchemaToolError(
                f"{path}:{lineno}: 承接 issue is empty — a registered difference with no owner "
                "never gets closed"
            )
        rows.append(DeviationRow(key, kind, summary, reason, issue, lineno))
    return rows


def load_apply_exceptions(path: Path) -> list[DiffItem]:
    """One `apply-exception:` item per object that a skipped statement would have created."""
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise SchemaToolError(
            f"{path} is missing — it is generated by scripts/build_upstream_schema.py and must be "
            "checked in next to contracts/upstream-schema.json"
        ) from None
    items: dict[tuple[str, str], DiffItem] = {}
    order: list[tuple[str, str]] = []
    for line in raw.splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("\t")]
        if len(parts) < 6:
            raise SchemaToolError(
                f"{path}: malformed row (want 6 tab-separated columns): {line[:120]!r}"
            )
        file, lineno, category, reason, objects = parts[0], parts[1], parts[2], parts[3], parts[4]
        if not objects:
            raise SchemaToolError(
                f"{path}: {file}:{lineno}: the skipped statement lists no object and no "
                "`statement:<file>:<line>` fallback — it would escape the deviation registry"
            )
        for token in objects.split(","):
            kind, _, name = token.partition(":")
            if not kind.strip() or not name.strip():
                raise SchemaToolError(f"{path}: {file}:{lineno}: cannot parse object {token!r}")
            key = (kind.strip(), name.strip())
            if key in items:
                items[key].detail.append(f"also skipped at {file}:{lineno}")
                continue
            items[key] = DiffItem(
                kind=key[0],
                key=key[1],
                category="apply-exception",
                summary=(
                    "apply-exception: upstream creates this, the snapshot built here cannot — "
                    f"{collapse_ws(reason)}"
                ),
                detail=[f"{category} at {file}:{lineno}"],
                source=f"{file}:{lineno}",
            )
            order.append(key)
    return [items[k] for k in order]


def _up_sql_files(directory: Path, *, recursive: bool) -> list[Path]:
    glob = directory.rglob if recursive else directory.glob
    files = sorted(p for p in glob("*.up.sql") if p.is_file())
    if not files:
        raise SchemaToolError(
            f"no *.up.sql migrations under {directory} — an empty apply set would make every "
            "upstream object look missing for the wrong reason"
        )
    return files


def dir_migrations(directory: Path) -> list[Path]:
    """Every `*.up.sql` directly under `directory`, sorted by name."""
    return _up_sql_files(directory, recursive=False)


def merged_migrations(directory: Path) -> list[Path]:
    """The runtime's real apply set: every `*.up.sql` under `directory`, recursively, by stem.

    Mirrors `mc_db::Migrator::load_dirs` — `upstream/001_init.up.sql` and `compat/535_x.up.sql`
    share one numbering space, ordered by that stem, and a duplicate stem is an error rather
    than a silent "last one wins".
    """
    by_stem: dict[str, list[Path]] = {}
    for path in _up_sql_files(directory, recursive=True):
        by_stem.setdefault(path.stem, []).append(path)
    clashes = {stem: [str(p) for p in ps] for stem, ps in by_stem.items() if len(ps) > 1}
    if clashes:
        raise SchemaToolError(
            f"duplicate migration version(s) under {directory} — keys must be unique: {clashes}"
        )
    return [ps[0] for _, ps in sorted(by_stem.items())]


# --------------------------------------------------------------------------- #
# the diff
# --------------------------------------------------------------------------- #


@dataclass
class DiffItem:
    kind: str
    key: str
    category: str
    summary: str
    detail: list[str] = field(default_factory=list)
    folded: dict[str, int] = field(default_factory=dict)
    source: str = ""
    #: a `differs` row whose only difference is `attnum` — the same set of columns, laid out
    #: in another order.  It is still a difference (the snapshot records position on purpose,
    #: so a reordered table is visible), but it is not a contract difference, so the report
    #: splits it out instead of letting it drown the ones that are.
    position_only: bool = False

    @property
    def ident(self) -> tuple[str, str, str]:
        return (self.key, self.kind, self.category)

    def folded_note(self) -> str:
        if not self.folded:
            return ""
        return "  (+" + ", ".join(f"{n} {k}" for k, n in sorted(self.folded.items())) + ")"

    def detail_note(self) -> str:
        if self.position_only:
            return "column order only (attnum)"
        return self.detail[0] if self.detail else ""

    def to_json(self) -> dict:
        return {
            "object": self.key,
            "kind": self.kind,
            "category": self.category,
            "summary": self.summary,
            "detail": self.detail,
            "folded": self.folded,
            "source": self.source,
            "position_only": self.position_only,
        }


def _clip(text: str, limit: int = 160) -> str:
    text = collapse_ws(text)
    return text if len(text) <= limit else text[: limit - 3] + "..."


def _compare_defs(mine: dict, theirs: dict) -> list[str]:
    """Per-field differences between two definitions of the same object."""
    detail = []
    for key in sorted(set(mine) | set(theirs)):
        a, b = mine.get(key), theirs.get(key)
        if a == b:
            continue
        if key in ("definition", "default") and (a or b):
            detail.append(f"{key}: repo={_clip(str(a))!r} upstream={_clip(str(b))!r}")
        else:
            detail.append(f"{key}: repo={a!r} upstream={b!r}")
    return detail


def diff_snapshots(mine: dict, theirs: dict) -> list[DiffItem]:
    """Compare two `object_map()`s, folding a missing/extra table's children into its row."""
    items: list[DiffItem] = []
    by_table: dict[str, DiffItem] = {}
    folded_tables: set[str] = set()

    def add_table(key: str, category: str, summary: str) -> None:
        item = DiffItem(kind="table", key=key, category=category, summary=summary)
        items.append(item)
        by_table[key] = item
        folded_tables.add(key)

    for kind, key in sorted(k for k in theirs if k[0] == "table" and k not in mine):
        add_table(
            key,
            "missing",
            "missing: present in the upstream snapshot, not created by this repo's migrations",
        )
    for kind, key in sorted(k for k in mine if k[0] == "table" and k not in theirs):
        add_table(
            key,
            "extra",
            "extra: created by this repo's migrations, absent from the upstream snapshot",
        )

    def fold_or_emit(kind: str, key: str, category: str, summary: str) -> bool:
        """Fold a child of a missing/extra table into that table's row.  True when folded."""
        if kind not in CHILD_KINDS:
            return False
        definition = mine.get((kind, key)) or theirs.get((kind, key)) or {}
        owner = definition.get("table", "")
        if owner not in folded_tables:
            return False
        by_table[owner].folded[kind] = by_table[owner].folded.get(kind, 0) + 1
        return True

    for kind, key in sorted(set(mine) & set(theirs)):
        detail = _compare_defs(mine[(kind, key)], theirs[(kind, key)])
        position_only = bool(detail) and all(d.startswith("position:") for d in detail)
        if kind == "table":
            if detail:
                items.append(
                    DiffItem(kind, key, "differs", "differs: same object, different definition", detail)
                )
            continue
        if fold_or_emit(kind, key, "differs", ""):
            continue
        if detail:
            items.append(
                DiffItem(
                    kind,
                    key,
                    "differs",
                    "differs: same object, different definition",
                    detail,
                    position_only=position_only,
                )
            )

    for kind, key in sorted(set(mine) - set(theirs)):
        if kind == "table" or fold_or_emit(kind, key, "extra", ""):
            continue
        items.append(
            DiffItem(
                kind,
                key,
                "extra",
                "extra: created by this repo's migrations, absent from the upstream snapshot",
            )
        )

    for kind, key in sorted(set(theirs) - set(mine)):
        if kind == "table" or fold_or_emit(kind, key, "missing", ""):
            continue
        items.append(
            DiffItem(
                kind,
                key,
                "missing",
                "missing: present in the upstream snapshot, not created by this repo's migrations",
            )
        )

    return items


def check_registry(
    items: list[DiffItem], rows: list[DeviationRow]
) -> tuple[list[DiffItem], list[DeviationRow], list[DeviationRow]]:
    """`(unregistered items, stale errors, stale warnings)`."""
    unregistered: list[DiffItem] = []
    for item in items:
        hits = [r for r in rows if r.matches(item)]
        if not hits:
            unregistered.append(item)
        for r in hits:
            r.covered += 1
            if not r.example:
                r.example = item.key
    stale_errors = [r for r in rows if not r.covered and r.category == "apply-exception"]
    stale_warnings = [r for r in rows if not r.covered and r.category != "apply-exception"]
    return unregistered, stale_errors, stale_warnings


def render_deviations(items: list[DiffItem]) -> str:
    """Skeleton registry rows; `原因` and `承接 issue` are empty on purpose."""
    lines = [
        "# skeleton rows from scripts/schema_drift.py --emit-deviations",
        "# 原因 / 承接 issue are empty on purpose — fill both in before adding a row to",
        "# contracts/schema-deviations.tsv, whose loader rejects empty ones.",
        "#",
    ]
    for item in sorted(items, key=lambda i: (i.category, i.kind, i.key)):
        lines.append("\t".join([item.key, item.kind, item.category + ":", "", ""]))
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# report
# --------------------------------------------------------------------------- #


def _render_table(rows: list[list[str]], headers: list[str], indent: str = "  ") -> list[str]:
    """Left-align `rows` under `headers`.  Stdlib only, no wrapping."""
    if not rows:
        return [f"{indent}(none)"]
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row[: len(headers)]):
            widths[i] = max(widths[i], len(cell))
    lines = [indent + "  ".join(h.ljust(widths[i]) for i, h in enumerate(headers)).rstrip()]
    for row in rows:
        cells = list(row[: len(headers)]) + [""] * (len(headers) - len(row))
        lines.append(indent + "  ".join(c.ljust(widths[i]) for i, c in enumerate(cells)).rstrip())
    return lines


def print_report(
    *,
    apply_set: str,
    files: list[Path],
    report,
    snapshot: dict,
    upstream: dict,
    items: list[DiffItem],
    deviations: list[DeviationRow],
    unregistered: list[DiffItem],
    stale_errors: list[DeviationRow],
    stale_warnings: list[DeviationRow],
    keep_db: bool,
    ok: bool,
) -> None:
    meta = upstream.get("meta", {})
    print(
        f"baseline  contracts/upstream-schema.json — upstream "
        f"{str(meta.get('upstream_commit', '?'))[:12]}, {meta.get('migrations_applied', '?')} "
        f"migrations, {len(upstream['objects'])} objects"
    )
    print(
        f"apply set {apply_set} — {len(files)} file(s), {report.statements} statements, "
        f"{len(report.applied)} applied, {len(report.skipped)} skipped"
    )
    print(
        f"scratch   {snapshot['meta']['database']}{'' if keep_db else ' (dropped)'} on "
        f"PostgreSQL {snapshot['meta']['server_version']} — {len(snapshot['objects'])} objects"
    )
    print()

    if items:
        rows = []
        for item in sorted(items, key=lambda i: (i.category, i.kind, i.key)):
            detail = item.folded_note().strip() or item.detail_note()
            rows.append([item.category, item.kind, item.key, detail])
        print(f"differences ({len(items)}):")
        for line in _render_table(rows, ["category", "kind", "object", "detail"]):
            print(line)
    else:
        print("differences: none — the two schemas are identical")

    by_category: dict[str, int] = {}
    for item in items:
        by_category[item.category] = by_category.get(item.category, 0) + 1
    if by_category:
        print()
        print("by category: " + ", ".join(f"{k}={v}" for k, v in sorted(by_category.items())))
        order_only = sum(1 for i in items if i.position_only)
        if order_only:
            print(
                f"            ({order_only} of the differs rows are column order only — same columns, "
                "different attnum; kept because a reordered table is a difference, not a contract change)"
            )
        folded: dict[str, int] = {}
        for item in items:
            for kind, count in item.folded.items():
                folded[kind] = folded.get(kind, 0) + count
        if folded:
            print(
                "            ("
                + ", ".join(f"{v} {k}" for k, v in sorted(folded.items()))
                + " folded into the missing/extra table rows)"
            )

    if report.unexpected:
        print()
        print(f"unexpected migration failures ({len(report.unexpected)}):")
        for s in report.unexpected:
            print(f"  {s.file}:{s.line} {collapse_ws(s.reason)}")
    if report.notices:
        print()
        print(f"guard notices ({len(report.notices)}) — upstream swallowed these at runtime:")
        for name, notice in report.notices:
            print(f"  {name}: {collapse_ws(notice)}")

    print()
    print(
        f"registry  {len(deviations)} row(s): {sum(1 for r in deviations if r.covered)} matched, "
        f"{len(stale_warnings)} stale (warning), {len(stale_errors)} stale (error)"
    )
    for row in stale_errors:
        print(f"  ERROR stale apply-exception row at line {row.line}: {row.key} ({row.kind})")
    for row in stale_warnings[:10]:
        print(f"  warn  stale row at line {row.line}: {row.key} ({row.kind}, {row.category})")

    if unregistered:
        print()
        print(f"unregistered differences ({len(unregistered)}) — run this to get skeleton rows:")
        print("  python3 scripts/schema_drift.py --emit-deviations")
        for line in _render_table(
            [[i.category, i.kind, i.key] for i in sorted(unregistered, key=lambda i: (i.kind, i.key))],
            ["category", "kind", "object"],
        ):
            print(line)

    print()
    print("OK — every difference is registered" if ok else "FAIL — drift is not fully registered")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument(
        "--db-url",
        default=os.environ.get("MULTICA_TEST_DATABASE_URL", ""),
        help="postgres:// URL of an existing database on the target server; the scratch database "
        "is created next to it (env: MULTICA_TEST_DATABASE_URL).  The password reaches the psql "
        "child through PGPASSWORD, never through its argv, so it cannot show up in `ps`.",
    )
    ap.add_argument("--db-name", default=DEFAULT_DB_NAME, help="name of the scratch database")
    ap.add_argument("--migrations", default=str(ROOT / DEFAULT_MIGRATIONS))
    ap.add_argument("--upstream-migrations", default=str(ROOT / DEFAULT_UPSTREAM_MIGRATIONS))
    ap.add_argument("--upstream-schema", default=str(ROOT / DEFAULT_UPSTREAM_SCHEMA))
    ap.add_argument("--deviations", default=str(ROOT / DEFAULT_DEVIATIONS))
    ap.add_argument("--exceptions", default=str(ROOT / DEFAULT_EXCEPTIONS))
    ap.add_argument(
        "--apply-set",
        choices=("local", "upstream"),
        default="local",
        help="local (default, the CI mode): the runtime's real apply set — every *.up.sql under "
        "migrations/, recursively, merged and ordered by file stem (upstream/ + compat/).  "
        "upstream: the vendored migrations/upstream/*.up.sql alone, no compat patches (W0-B2 "
        "exploration; extension-gated statements are tolerated).",
    )
    ap.add_argument(
        "--lenient",
        action="store_true",
        help="record unexpected migration failures and carry on instead of failing the run",
    )
    ap.add_argument("--keep-db", action="store_true", help="leave the scratch database behind")
    ap.add_argument(
        "--emit-deviations",
        action="store_true",
        help="print skeleton registry rows for the unregistered differences",
    )
    ap.add_argument("--json", action="store_true", help="machine-readable report on stdout")
    ap.add_argument("--quiet", action="store_true", help="print nothing; the exit code is the answer")
    args = ap.parse_args(argv)

    if not args.db_url:
        sys.stderr.write("error: no database URL: pass --db-url or set MULTICA_TEST_DATABASE_URL\n")
        return 2

    try:
        parse_db_url(args.db_url)
        upstream = load_snapshot(Path(args.upstream_schema))
        deviations = load_deviations(Path(args.deviations), allow_missing=args.emit_deviations)
        exceptions = load_apply_exceptions(Path(args.exceptions))
        if args.apply_set == "upstream":
            files = dir_migrations(Path(args.upstream_migrations))
        else:
            files = merged_migrations(Path(args.migrations))
    except SchemaToolError as exc:
        sys.stderr.write(f"error: {exc}\n")
        return 2

    # `local` is strict: the runtime's own set must apply cleanly.  `upstream` is the
    # exploration mode and tolerates extension-gated statements, as does `--lenient`.
    strict = not (args.lenient or args.apply_set == "upstream")

    try:
        with ScratchDatabase(args.db_url, args.db_name, keep=args.keep_db) as db:
            available = db.available_extensions()
            report = apply_migrations(db, files, available=available, strict=False)
            snapshot = build_snapshot(
                db,
                label=f"repo-{args.apply_set}",
                source="the migrations/*.up.sql files this repo applies",
            )
    except SchemaToolError as exc:
        sys.stderr.write(f"error: {exc}\n")
        return 2

    items = diff_snapshots(object_map(snapshot), object_map(upstream)) + exceptions
    unregistered, stale_errors, stale_warnings = check_registry(items, deviations)
    unexpected_failure = bool(report.unexpected) and strict
    ok = not unregistered and not stale_errors and not unexpected_failure

    if args.emit_deviations and not args.quiet and not args.json:
        print(render_deviations(unregistered))

    if args.json:
        counts: dict[str, int] = {}
        for item in items:
            counts[item.category] = counts.get(item.category, 0) + 1
        payload = {
            "ok": ok,
            "apply_set": args.apply_set,
            "database": snapshot["meta"]["database"],
            "server_version": snapshot["meta"]["server_version"],
            "upstream": {
                "snapshot": args.upstream_schema,
                "commit": upstream["meta"].get("upstream_commit", ""),
                "repo": upstream["meta"].get("upstream_repo", ""),
                "migrations": upstream["meta"].get("migrations_applied"),
                "objects": len(upstream["objects"]),
                "sha256": sha256_of(Path(args.upstream_schema)),
            },
            "repo": {
                "objects": len(snapshot["objects"]),
                "migrations": [{"file": p.name, "sha256": sha256_of(p)} for p in files],
                "statements": report.statements,
                "applied": len(report.applied),
                "extensions": snapshot["meta"]["extensions"],
            },
            "skipped": [
                {
                    "file": s.file,
                    "line": s.line,
                    "category": s.category,
                    "reason": collapse_ws(s.reason),
                    "objects": [f"{k}:{v}" for k, v in skip_object_keys(s)],
                }
                for s in report.skipped
            ],
            "unexpected_skips": [
                f"{s.file}:{s.line} {s.category} {collapse_ws(s.reason)}" for s in report.unexpected
            ],
            "guard_notices": [f"{name}: {collapse_ws(n)}" for name, n in report.notices],
            "counts": counts,
            "position_only": sum(1 for i in items if i.position_only),
            "folded": {
                k: sum(i.folded.get(k, 0) for i in items)
                for k in sorted({k for i in items for k in i.folded})
            },
            "differences": [i.to_json() for i in items],
            "unregistered": [i.to_json() for i in unregistered],
            "registry": {
                "file": args.deviations,
                "rows": len(deviations),
                "matched": sum(1 for r in deviations if r.covered),
                "stale_errors": [
                    {"line": r.line, "object": r.key, "kind": r.kind, "category": r.category}
                    for r in stale_errors
                ],
                "stale_warnings": [
                    {"line": r.line, "object": r.key, "kind": r.kind, "category": r.category}
                    for r in stale_warnings
                ],
                "coverage": [
                    {
                        "line": r.line,
                        "object": r.key,
                        "kind": r.kind,
                        "category": r.category,
                        "covers": r.covered,
                        "example": r.example,
                    }
                    for r in deviations
                ],
            },
            "extensions_available": sorted(available),
        }
        json.dump(payload, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
    elif not args.quiet and not args.emit_deviations:
        print_report(
            apply_set=args.apply_set,
            files=files,
            report=report,
            snapshot=snapshot,
            upstream=upstream,
            items=items,
            deviations=deviations,
            unregistered=unregistered,
            stale_errors=stale_errors,
            stale_warnings=stale_warnings,
            keep_db=args.keep_db,
            ok=ok,
        )

    return 0 if ok else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BrokenPipeError:  # `| head` — close stdout without a traceback
        try:
            sys.stdout.close()
        finally:
            os._exit(0)
    except KeyboardInterrupt:
        raise SystemExit(130)
