#!/usr/bin/env python3
"""Upstream handler index: ``testHandler.<Handler>`` → the route it serves.

Upstream's handler tests drive handlers directly (``testHandler.GetX(w, req)``), so
the only way to know which route such a call exercises is to read the router.  This
module joins two things that are already committed and reviewable:

* ``docs/fixtures/upstream-routes.tsv`` — ``method  path  owner  # router.go:N``;
* the second argument of the chi registration on that cited line
  (``r.Get("/api/x", h.GetX)`` → ``h.GetX``).

It emits ``docs/fixtures/handler-routes.tsv`` (``handler  method  path  owner``), the
lookup rule I4 (``docs/42`` §6.3 step 6) uses to accept a direct-handler call site.
Rows whose registration is not ``h.<Exported>`` — 3 ``health.<fn>``, 1 call
expression, 1 inline closure — are recorded with a ``-`` handler so the table is a
complete census of the route table rather than a filtered view.

The path of a registration written as a package constant cannot be re-checked here;
those rows trust the line number ``upstream-routes.tsv`` recorded, and the count is
published in the generated header instead of being hidden.

Regenerate / verify::

    python3 scripts/upstream_handler_index.py --upstream <checkout> --write-handler-routes
    python3 scripts/upstream_handler_index.py --upstream <checkout> --check-handler-routes
    python3 scripts/upstream_handler_index.py --upstream <checkout> --list-handlers
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Any, Optional

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
ROUTES_TSV = os.path.join(REPO, "docs", "fixtures", "upstream-routes.tsv")
HANDLER_ROUTES_TSV = os.path.join(REPO, "docs", "fixtures", "handler-routes.tsv")
ROUTER_REL = os.path.join("server", "cmd", "server", "router.go")

#: The chi registration call head on the cited ``router.go`` line.
CALL_HEAD = re.compile(r"\.(?:Get|Post|Put|Patch|Delete|Head|Options)\s*\(")
#: `docs/fixtures/upstream-routes.tsv` rows: `GET\t/api/chat/history\tM4\t# router.go:2373`.
ROUTE_ROW = re.compile(
    r"^(?P<method>[A-Z]+)\t(?P<path>[^\t]+)\t(?P<owner>[^\t#]*)\t#\s*router\.go:(?P<line>\d+)\s*$"
)
#: The second argument of a chi registration: `r.Get("/api/x", h.GetX)`.
ROUTE_HANDLER = re.compile(r",\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\)\s*(?://.*)?$")
ROUTE_INLINE = re.compile(r",\s*(?:func\s*\(|http\.HandlerFunc\s*\()")

#: Receiver the handler suite registers its methods on (`h.GetChatChannelHistory`).
#: Only 4 of the 472 committed route rows register anything else, and none of those
#: is a method a test could call as `testHandler.X`; checking the receiver keeps a
#: package-level function out of the handler index.
HANDLER_RECV = "h"

def route_rows(path: str = ROUTES_TSV) -> list[dict[str, Any]]:
    """Parse the committed upstream route table."""
    if not os.path.isfile(path):
        raise SystemExit(
            "extract_i4_direct_handler: %s is missing; it is generated by "
            "scripts/gen_upstream_routes.py (docs/42 §6.3 step 6)" % path
        )
    rows: list[dict[str, Any]] = []
    for raw in open(path, encoding="utf-8"):
        if raw.startswith("#") or not raw.strip():
            continue
        m = ROUTE_ROW.match(raw.rstrip("\n"))
        if m is None:
            raise SystemExit("extract_i4_direct_handler: unparsable route row: %r" % raw)
        rows.append(
            {
                "method": m.group("method"),
                "path": m.group("path"),
                "owner": m.group("owner").strip(),
                "line": int(m.group("line")),
            }
        )
    if not rows:
        raise SystemExit("extract_i4_direct_handler: %s has no route rows" % path)
    return rows


def _split_text_args(text: str, start: int) -> tuple[list[str], int]:
    """Split a Go call's arguments, honouring nesting and string quotes."""
    depth, out, cur = 0, [], []
    quote = None
    i = start
    while i < len(text):
        ch = text[i]
        if quote is not None:
            cur.append(ch)
            if ch == "\\":
                if i + 1 < len(text):
                    cur.append(text[i + 1])
                    i += 2
                    continue
            elif ch == quote:
                quote = None
            i += 1
            continue
        if ch in '\'"`':
            quote = ch
        elif ch in "([{":
            depth += 1
        elif ch in ")]}":
            if depth == 0:
                out.append("".join(cur))
                return out, i
            depth -= 1
        elif ch == "," and depth == 0:
            out.append("".join(cur))
            cur = []
            i += 1
            continue
        cur.append(ch)
        i += 1
    out.append("".join(cur))
    return out, len(text)


def _second_arg(lines: list[str], row: dict[str, Any]) -> Optional[tuple[str, bool]]:
    """``(second argument, path was a literal)`` for the cited registration.

    The cited line is read first and a few lines after it, so a registration spread
    over two lines is still found; a line whose path literal contradicts the table
    is rejected rather than read.  A path written as a package constant
    (``r.Get(publicapiv1.PathContext, h.GetPluginContext)``) cannot be checked this
    way — those rows trust the line number ``scripts/gen_upstream_routes.py``
    recorded when it resolved the constant, and the count is published in the
    table's header.
    """
    i = row["line"] - 1
    for start in range(i, min(i + 6, len(lines))):
        m = CALL_HEAD.search(lines[start])
        if m is None:
            continue
        text = " ".join(lines[start : start + 4])
        args, _end = _split_text_args(text, m.end())
        if len(args) < 2:
            continue
        first, expr = args[0].strip(), args[1].strip()
        lit = re.fullmatch(r'"([^"]*)"', first)
        if lit is not None and not _suffix_match(row["path"], lit.group(1)):
            continue
        if expr:
            return expr, lit is not None
    return None


def classify_registration(expr: Optional[str]) -> tuple[str, Optional[str]]:
    """``(kind, handler)`` for a registration's second argument.

    ``handler`` is the name a test can call as ``testHandler.<handler>(w, req)`` —
    only the suite's own exported method (``h.GetChatChannelHistory``) qualifies.  A
    package-level function (``health.liveHandler``), a call expression and an inline
    closure are each recorded as themselves/``-`` and kept out of the index: a test
    cannot call them that way, so treating them as callable would be a guess.
    """
    if expr is None:
        return "none", None
    if re.match(r"^func\s*\(", expr):
        return "inline", None
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_.]*$", expr):
        return "call", None
    if expr.count(".") == 1:
        recv, name = expr.split(".")
        if recv == HANDLER_RECV and re.match(r"^[A-Z][A-Za-z0-9_]*$", name):
            return "handler", name
    return "qualified", None


def _suffix_match(row_path: str, literal: str) -> bool:
    """Whether a registered path ends with the literal on the same line.

    Nested registrations (``r.Route("/api/squads/{id}", …)`` …
    ``r.Get("/members/status", h.ListSquadMemberStatus)``) cite the inner line, so
    the literal is compared as a path suffix rather than for equality.
    """
    a, b = row_path.rstrip("/"), literal.rstrip("/")
    if literal in ("/", ""):
        # `r.Get("/", h.X)` inside `r.Route("/api/x", …)` registers the group's own
        # root; the table already composed the full path, so "/" anchors it.
        return True
    return a == b or (bool(b) and a.endswith(b) and b.startswith("/"))


def handler_index(
    root: str, rows: Optional[list[dict[str, Any]]] = None
) -> tuple[dict[str, list[dict[str, Any]]], list[dict[str, Any]]]:
    """Map handler name → the routes registering it, for one upstream checkout.

    Also returns the join of the route table with ``router.go`` — one record per
    route: the raw second argument, its kind, and the handler name when callable.
    That join is what ``docs/fixtures/handler-routes.tsv`` publishes.
    """
    rows = route_rows() if rows is None else rows
    with open(os.path.join(root, ROUTER_REL), encoding="utf-8", errors="replace") as fh:
        lines = fh.read().splitlines()
    index: dict[str, list[dict[str, Any]]] = {}
    joined: list[dict[str, Any]] = []
    for row in rows:
        got = _second_arg(lines, row)
        kind, name = classify_registration(got[0] if got else None)
        if kind == "none":
            raise SystemExit(
                "extract_i4_direct_handler: cannot read the registration of %s %s "
                "(router.go:%d); the committed route table and the checkout disagree — "
                "regenerate docs/fixtures/upstream-routes.tsv with scripts/gen_upstream_routes.py"
                % (row["method"], row["path"], row["line"])
            )
        if kind == "handler":
            index.setdefault(name, []).append(row)
        joined.append(
            {"row": row, "expr": got[0], "kind": kind, "handler": name, "literal_path": got[1]}
        )
    if not index:
        raise SystemExit("extract_i4_direct_handler: no handler registrations found in %s" % root)
    return index, joined


def render_handler_routes(joined: list[dict[str, Any]], commit: str) -> str:
    """The committed handler → route table (recomputable, cites its two inputs)."""
    counts: dict[str, int] = {}
    for j in joined:
        counts[j["kind"]] = counts.get(j["kind"], 0) + 1
    out = [
        "# handler-routes.tsv — upstream registration → route key.",
        "#",
        "# Consumed by scripts/extract_i4_direct_handler.py (rule I4, docs/42 §6.3): the",
        "# `handler` column is the name a handler test can call as `testHandler.<handler>(w, req)`.",
        "# source: docs/fixtures/upstream-routes.tsv joined with the second argument of the",
        "#         server/cmd/server/router.go registration on the line that table cites.",
        "# upstream commit: %s" % commit,
        "# regenerate: python3 scripts/upstream_handler_index.py --upstream <checkout> "
        "--write-handler-routes",
        "# rows: %d routes — %d callable handler methods (`h.<Name>`), %d otherwise qualified "
        "(`pkg.fn`), %d call expressions, %d inline closures; `-` means a test cannot call "
        "the route's registration as `testHandler.X`, so rule I4 never emits from it. "
        "%d of %d rows cite a path written as a package constant, which cannot be "
        "re-checked here; those rows trust the line number upstream-routes.tsv recorded."
        % (
            len(joined),
            counts.get("handler", 0),
            counts.get("qualified", 0),
            counts.get("call", 0),
            counts.get("inline", 0),
            sum(1 for j in joined if not j["literal_path"]),
            len(joined),
        ),
        "#",
        "# handler\tmethod\tpath\towner\t# router.go:N",
    ]
    order = {"handler": 0, "qualified": 1, "call": 2, "inline": 3}
    for j in sorted(
        joined,
        key=lambda j: (
            order.get(j["kind"], 9),
            j["handler"] or j["expr"] or "",
            j["row"]["method"],
            j["row"]["path"],
        ),
    ):
        label = j["handler"] or (j["expr"] if j["kind"] == "qualified" else "-")
        out.append(
            "%s\t%s\t%s\t%s\t# router.go:%d"
            % (label, j["row"]["method"], j["row"]["path"], j["row"]["owner"], j["row"]["line"])
        )
    return "\n".join(out) + "\n"


def write_handler_routes(root: str, out_path: str, commit: str) -> None:
    """Write the table; used by the module CLI (``--write-handler-routes``)."""
    _index, joined = handler_index(root)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(render_handler_routes(joined, commit))
    print("wrote %s (%d routes)" % (out_path, len(joined)))

# --------------------------------------------------------------------------- #
# CLI (route table only; the extractor calls run() in-process)
# --------------------------------------------------------------------------- #


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--upstream", required=True, help="path to an upstream multica checkout")
    ap.add_argument(
        "--write-handler-routes",
        nargs="?",
        const=HANDLER_ROUTES_TSV,
        help="write the table (default %s)" % HANDLER_ROUTES_TSV,
    )
    ap.add_argument(
        "--check-handler-routes",
        nargs="?",
        const=HANDLER_ROUTES_TSV,
        help="verify the table byte-for-byte, write nothing",
    )
    ap.add_argument("--list-handlers", action="store_true", help="print handler → routes")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.upstream)
    if not os.path.isdir(os.path.join(root, "server")):
        print("error: --upstream %s is not a multica checkout" % root, file=sys.stderr)
        return 2
    commit = "unknown"
    pin = os.path.join(REPO, "contracts", "golden", "PIN")
    if os.path.isfile(pin):
        for raw in open(pin, encoding="utf-8"):
            if raw.startswith("upstream_commit "):
                commit = raw.split(None, 1)[1].strip()
    index, joined = handler_index(root)
    if args.list_handlers:
        for handler in sorted(index):
            for row in index[handler]:
                print("%s\t%s\t%s\trouter.go:%d" % (handler, row["method"], row["path"], row["line"]))
        print("%d handlers, %d routes" % (len(index), len(joined)))
        return 0
    text = render_handler_routes(joined, commit)
    if args.check_handler_routes:
        if not os.path.isfile(args.check_handler_routes):
            print("error: %s is missing" % args.check_handler_routes, file=sys.stderr)
            return 1
        with open(args.check_handler_routes, encoding="utf-8") as fh:
            if fh.read() != text:
                print(
                    "%s drifted: regenerate it with --write-handler-routes" % args.check_handler_routes,
                    file=sys.stderr,
                )
                return 1
        print("%s matches the router (rule I4, docs/42 §6.3)" % args.check_handler_routes)
        return 0
    out = args.write_handler_routes or HANDLER_ROUTES_TSV
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d routes, %d handlers)" % (out, len(joined), len(index)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
